on:
  push:
  workflow_dispatch:

env:
  IMAGE: ghcr.io/${{ github.repository }}:latest
  FROM_IMAGE: mcr.microsoft.com/windows/nanoserver:1803-amd64

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create a Dockerfile
        shell: bash
        run: |
          echo 'FROM ${{ env.FROM_IMAGE }}' > Dockerfile
          echo 'ENTRYPOINT ["echo", "Hello from ${{ github.repository }}!"]' >> Dockerfile

      - name: Build image
        shell: bash
        run: docker build . -t ${IMAGE,,} # lowercase IMAGE

      - name: Login to ghcr.io
        shell: bash
        run: docker login https://ghcr.io -u token --password-stdin <<< ${{ github.token }}

      - name: Publish image
        shell: bash
        run: docker push ${IMAGE,,} # lowercase IMAGE
